# Generated by Django 3.0.5 on 2020-05-01 01:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoptask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sku', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword])),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', related_query_name='catalog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
                'db_table': 'shoptask_catalog',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='bill',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill_summary',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='merchant',
            field=models.TextField(blank=True, help_text='Who merchant prefered by Customer?Something like Alfamart at Paal Merah'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.TextField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accept', 'Accept'), ('assigned', 'Assigned'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('done', 'Done')], default='submitted', max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('label', models.CharField(help_text='Eg; Home, Office, ect', max_length=255)),
                ('recipient', models.CharField(blank=True, help_text='Eg; Abu Bakar Ash-Shiddiq', max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('address', models.TextField(help_text='Complete address include number, building, street,province, district and other detail.')),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('notes', models.TextField(blank=True, help_text='Eg; Put in garage')),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings_address', related_query_name='shipping_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shippings Address',
                'db_table': 'shoptask_shipping_address',
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_shippings', related_query_name='purchase_shipping', to='shoptask.Purchase')),
                ('shipping_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_shippings', related_query_name='purchase_shipping', to='shoptask.ShippingAddress')),
            ],
            options={
                'verbose_name': 'Purchase Shipping',
                'verbose_name_plural': 'Purchase Shippings',
                'db_table': 'shoptask_purchase_shipping',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_catalogs', related_query_name='goods_catalog', to='shoptask.Catalog')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_catalogs', related_query_name='goods_catalog', to='shoptask.Goods')),
            ],
            options={
                'verbose_name': 'Goods Catalog',
                'verbose_name_plural': 'Goods Catalogs',
                'db_table': 'shoptask_goods_catalog',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True)),
                ('column', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_status', related_query_name='log_status', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(app_label='shoptask'), on_delete=django.db.models.deletion.CASCADE, related_name='logs_status', related_query_name='log_status', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Log Status',
                'verbose_name_plural': 'Logs Status',
                'db_table': 'shoptask_change_log',
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.BooleanField(blank=True, default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('catalog_count', models.IntegerField(default=0, editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', related_query_name='category', to='shoptask.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'shoptask_category',
                'abstract': False,
            },
        ),
    ]
