# Generated by Django 3.0.6 on 2020-05-11 14:24

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0006_auto_20200508_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accept', 'Accept'), ('assigned', 'Assigned'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('done', 'Done')], default='draft', max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
        migrations.AlterField(
            model_name='purchasestatuschange',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accept', 'Accept'), ('assigned', 'Assigned'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('done', 'Done')], max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
        migrations.AlterField(
            model_name='purchasestatuschange',
            name='old_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accept', 'Accept'), ('assigned', 'Assigned'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('done', 'Done')], max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
    ]
