# Generated by Django 3.0.6 on 2020-05-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0007_auto_20200511_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='purchase',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='goods', related_query_name='goods', to='shoptask.Purchase'),
        ),
    ]
