# Generated by Django 3.0.6 on 2020-05-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0008_auto_20200512_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', related_query_name='catalog', to='shoptask.Category'),
        ),
    ]
