# Generated by Django 3.0.6 on 2020-05-17 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0010_auto_20200513_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsextracharge',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='catalogattribute',
            name='metric',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('hg', 'Ons'), ('g', 'Gram'), ('mg', 'Miligram'), ('pack', 'Bungkus'), ('piece', 'Buah'), ('bunch', 'Ikat'), ('sack', 'Karung / Sak'), ('unit', 'Unit'), ('km', 'Kilometer'), ('m', 'Meter'), ('cm', 'Sentimeter'), ('mm', 'Milimeter')], max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
        migrations.AlterField(
            model_name='goodscatalog',
            name='goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_catalogs', related_query_name='goods_catalog', to='shoptask.Goods'),
        ),
    ]
