# Generated by Django 3.0.6 on 2020-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0012_auto_20200517_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(blank=True, default=1)),
                ('icon', models.ImageField(blank=True, max_length=500, upload_to='images/icon/brand')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('catalog_count', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'shoptask_brand',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, upload_to='images/icon/category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', related_query_name='catalog', to='shoptask.Brand'),
        ),
    ]
