# Generated by Django 3.0.6 on 2020-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0013_auto_20200517_2128'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='goodscatalog',
            constraint=models.UniqueConstraint(fields=('goods', 'catalog'), name='unique_goods_catalog'),
        ),
    ]
