# Generated by Django 3.0.6 on 2020-05-18 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0017_auto_20200518_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscatalog',
            name='goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_catalogs', related_query_name='goods_catalog', to='shoptask.Goods'),
        ),
    ]
