# Generated by Django 3.0.6 on 2020-05-22 22:01

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0018_auto_20200518_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='necessary',
            name='goods_count',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='bill_summary',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='goods_count',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='necessary_count',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='default_metric',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('hg', 'Ons'), ('g', 'Gram'), ('mg', 'Miligram'), ('liter', 'Liter'), ('pack', 'Bungkus'), ('pouch', 'Kantung'), ('bottle', 'Botol'), ('piece', 'Buah'), ('bunch', 'Ikat'), ('sack', 'Karung / Sak'), ('unit', 'Unit')], max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
        migrations.AlterField(
            model_name='catalogattribute',
            name='metric',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('hg', 'Ons'), ('g', 'Gram'), ('mg', 'Miligram'), ('liter', 'Liter'), ('pack', 'Bungkus'), ('pouch', 'Kantung'), ('bottle', 'Botol'), ('piece', 'Buah'), ('bunch', 'Ikat'), ('sack', 'Karung / Sak'), ('unit', 'Unit'), ('km', 'Kilometer'), ('m', 'Meter'), ('cm', 'Sentimeter'), ('mm', 'Milimeter')], max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
        migrations.AlterField(
            model_name='extracharge',
            name='metric',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('hg', 'Ons'), ('g', 'Gram'), ('mg', 'Miligram'), ('liter', 'Liter'), ('pack', 'Bungkus'), ('pouch', 'Kantung'), ('bottle', 'Botol'), ('piece', 'Buah'), ('bunch', 'Ikat'), ('sack', 'Karung / Sak'), ('unit', 'Unit'), ('km', 'Kilometer'), ('m', 'Meter'), ('cm', 'Sentimeter'), ('mm', 'Milimeter'), ('kg', 'Kilogram'), ('hg', 'Ons'), ('g', 'Gram'), ('mg', 'Miligram')], max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
        migrations.AlterField(
            model_name='goods',
            name='metric',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('hg', 'Ons'), ('g', 'Gram'), ('mg', 'Miligram'), ('liter', 'Liter'), ('pack', 'Bungkus'), ('pouch', 'Kantung'), ('bottle', 'Botol'), ('piece', 'Buah'), ('bunch', 'Ikat'), ('sack', 'Karung / Sak'), ('unit', 'Unit')], max_length=255, validators=[django.core.validators.RegexValidator(message='Can only contain the letters a-z and underscores.', regex='^[a-zA-Z_][a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
    ]
