# Generated by Django 3.0.6 on 2020-05-22 22:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0019_auto_20200523_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('schedule_date', models.DateField()),
                ('schedule_time_start', models.TimeField()),
                ('schedule_time_end', models.TimeField()),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'shoptask_purchase_delivery',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='PurchaseShipping',
        ),
        migrations.AddField(
            model_name='purchasedelivery',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_deliveries', related_query_name='purchase_delivery', to='shoptask.Purchase'),
        ),
        migrations.AddField(
            model_name='purchasedelivery',
            name='shipping_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_deliveries', related_query_name='purchase_delivery', to='shoptask.ShippingAddress'),
        ),
    ]
