# Generated by Django 3.0.6 on 2020-05-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0021_auto_20200523_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedelivery',
            name='schedule_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchasedelivery',
            name='schedule_time_end',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchasedelivery',
            name='schedule_time_start',
            field=models.TimeField(blank=True),
        ),
    ]
