# Generated by Django 3.0.6 on 2020-05-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptask', '0022_auto_20200523_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedelivery',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedelivery',
            name='schedule_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedelivery',
            name='schedule_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
