# Generated by Django 3.0.6 on 2020-05-28 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('shoptask', '0023_auto_20200523_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-date_created'], 'verbose_name': 'Change Log', 'verbose_name_plural': 'Change Logs'},
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelogs', related_query_name='changelog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(app_label='shoptask'), on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', related_query_name='changelog', to='contenttypes.ContentType'),
        ),
        migrations.AlterModelTable(
            name='changelog',
            table='shoptask_changelog',
        ),
    ]
